
<script>
jQuery(document).ready(function() {
	if(jQuery("#slider_list").length){ 
				jQuery('#slider_list').carouFredSel({
					responsive: true,
					width: '100%',
					prev: '.slider-sidebar-prev',
					next: '.slider-sidebar-next',
					pagination:'.slider-sidebar-pager',
					scroll: 1,
					auto	: {
			    		play	: 1,
				    	timeoutDuration :7000
				    },
					items: {
						visible: {
							min: 1,
							max: 1
						},
						width:270,
						height: 'variable'
					},
					mousewheel: true,
					swipe: {
						onMouse: true,
						onTouch: true
					}
				});
			};
			
		});
</script>
<?php $suffix = strtolower($this->getNameInLayout()); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget-catalogsale-products-carousel block" id="<?php echo $suffix ?>">
	<div class="block-title">
        <strong><span><?php echo $this->__('Special products') ?></span></strong>
    </div>
      <div class="block-content">
      	<ul id="slider_list" class="mini-products-list">
      	  <?php foreach ($_products->getItems() as $_product): ?>
      	  <li>
      	    	<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(90, 129) ?>"  alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
      	    	<div class="product-details">
      	    	    <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
      	    	    <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
      	    	    <?php if ($_product->getIsSalable()): ?>
      	    	        <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a>
      	    	    <?php else: ?>
      	    	        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
      	    	    <?php endif; ?>
      	    	</div>
      	  </li>
      	  <?php endforeach ?>
      	</ul>
      	<!-- <div class="slider-sidebar-pager"></div> -->
      	<div class="slider-sidebar-next">next</div>
      	<div class="slider-sidebar-prev">prev</div>
      	<div class="clear"></div>
      </div>
</div>
<?php endif; ?>

